### ISSUE TITLE
Cannot find a valid baseurl for repo error after upgrading from 2.0.0 to 2.10

### ISSUE THREAD

**Issue by fletchowns** [chef-cookbooks/yum-epel#43] opened 2016-12-23 03:11 UTC
### Cookbook version
2.1.0

### Chef-client version
12.10.24

### Platform Details
Red Hat Enterprise Linux Server release 7.2 (Maipo) on AWS, based on ami-d1315fb1

With version 2.0.0 of the yum-epel cookbook, I had this in epel.repo:
```
[ec2-user@mybox ~]$ cat /etc/yum.repos.d/epel.repo
# This file was generated by Chef
# Do NOT modify this file by hand.

[epel]
name=Extra Packages for $releasever - $basearch
enabled=1
failovermethod=priority
gpgcheck=1
gpgkey=https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7
mirrorlist=http://mirrors.fedoraproject.org/mirrorlist?repo=epel-7&arch=$basearch
```

After updating to 2.1.0 and running a converge it changed it to this:
```
[ec2-user@mybox ~]$ cat /etc/yum.repos.d/epel.repo
# This file was generated by Chef
# Do NOT modify this file by hand.

[epel]
name=Extra Packages for $releasever - $basearch
enabled=1
failovermethod=priority
gpgcheck=1
gpgkey=https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-$releasever
mirrorlist=http://mirrors.fedoraproject.org/mirrorlist?repo=epel-$releasever&arch=$basearch
```

(differences on the gpgkey and mirrorlist lines)

Now everything I try to do with yum results in errors:
```
[ec2-user@mybox ~]$ sudo yum makecache
Loaded plugins: amazon-id, rhui-lb, search-disabled-repos


 One of the configured repositories failed (Unknown),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Disable the repository, so yum won't use it by default. Yum will then
        just ignore the repository until you permanently enable it again or use
        --enablerepo for temporary usage:

            yum-config-manager --disable <repoid>

     4. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=<repoid>.skip_if_unavailable=true

Cannot find a valid baseurl for repo: epel/7Server/x86_64
```

**Comment by jwadolowski** [comment] 2017-01-02 16:01
Here's the stderr I got:

```
STDERR: yum-dump Repository Error: Cannot find a valid baseurl for repo: epel/7Server/x86_64
```

Apparently `$releasever` resolves to `7Server` on RHEL.

http://mirrors.fedoraproject.org/mirrorlist?repo=epel-7Server&arch=x86_64 returns just comments, but valid list of mirros gets back when you open this: http://mirrors.fedoraproject.org/mirrorlist?repo=epel-7&arch=x86_64

**Comment by erinn** [comment] 2017-01-03 08:18
This could also be considered an issue with the EPEL repo itself, 
http://mirrors.fedoraproject.org/mirrorlist?repo=epel-6Server&arch=x86_64 does work, but not 7Server, either way it should probably be fixed, tripped me up for a good long time.

**Comment by jwadolowski** [comment] 2017-01-03 10:46
Oh, that's a good catch @erinn. I haven't spotted it works well for `6Server` parameter.

**Comment by tas50** [comment] 2017-01-05 02:16
I'm going to revert the bit that changed over to the release string from redhat. I'm also going to make a note about this since I believe we've run into this issue in multiple repos

**Comment by tas50** [comment] 2017-01-05 03:53
Fixed in #44

**Comment by tas50** [comment] 2017-01-05 19:44
2.1.1 fixes this. Sorry about the regression.

**Closed by tas50** 2017-01-05 19:44 UTC

**Comment by fletchowns** [comment] 2017-01-06 01:37
Just updated to 2.1.1, didn't encounter any issues. Thanks for the quick turnaround!
